import type { GalleryItem } from "@/lib/types"

export const mockGallery: GalleryItem[] = [
  {
    id: "gal-1",
    titleFr: "Récolte de maïs",
    titleEn: "Maize harvest",
    imageUrl: "/images/gallery-field-1.png",
    category: "terrain",
    captionFr: "Nos agriculteurs partenaires récoltent le maïs à Kabare.",
    captionEn: "Our partner farmers harvesting maize in Kabare.",
    type: "image",
    order: 1,
    createdAt: "2024-09-01T00:00:00.000Z",
  },
  {
    id: "gal-2",
    titleFr: "Atelier de production",
    titleEn: "Production workshop",
    imageUrl: "/images/gallery-production-1.png",
    category: "produits",
    captionFr: "Transformation des céréales dans notre atelier de Bukavu.",
    captionEn: "Cereal processing in our Bukavu workshop.",
    type: "image",
    order: 2,
    createdAt: "2024-09-05T00:00:00.000Z",
  },
  {
    id: "gal-3",
    titleFr: "Distribution communautaire",
    titleEn: "Community distribution",
    imageUrl: "/images/gallery-event-1.png",
    category: "evenements",
    captionFr: "Distribution de farines enrichies dans un centre de santé.",
    captionEn: "Distribution of enriched flours at a health centre.",
    type: "image",
    order: 3,
    createdAt: "2024-10-10T00:00:00.000Z",
  },
  {
    id: "gal-4",
    titleFr: "L'équipe terrain",
    titleEn: "The field team",
    imageUrl: "/images/gallery-team-1.png",
    category: "equipe",
    captionFr: "Notre équipe lors d'une visite aux coopératives.",
    captionEn: "Our team during a visit to the cooperatives.",
    type: "image",
    order: 4,
    createdAt: "2024-10-15T00:00:00.000Z",
  },
  {
    id: "gal-5",
    titleFr: "Champs au lever du soleil",
    titleEn: "Fields at sunrise",
    imageUrl: "/images/gallery-field-2.png",
    category: "terrain",
    captionFr: "Les champs verdoyants du Sud-Kivu au petit matin.",
    captionEn: "The green fields of South Kivu in the early morning.",
    type: "image",
    order: 5,
    createdAt: "2024-11-01T00:00:00.000Z",
  },
  {
    id: "gal-6",
    titleFr: "Présentation produit",
    titleEn: "Product showcase",
    imageUrl: "/images/gallery-production-2.png",
    category: "produits",
    captionFr: "Emballage et contrôle qualité de SUPER ENERGY FARINA.",
    captionEn: "Packaging and quality control of SUPER ENERGY FARINA.",
    type: "image",
    order: 6,
    createdAt: "2024-11-05T00:00:00.000Z",
  },
]
